// <auto-generated />
using System;
using FlameReactor.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlameReactor.DB.Migrations
{
    [DbContext(typeof(FlameReactorContext))]
    [Migration("20210610162922_Breedings")]
    partial class Breedings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("FlameReactor.DB.Models.AccessEvent", b =>
                {
                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Timestamp", "IPAddress");

                    b.ToTable("AccessEvent");
                });

            modelBuilder.Entity("FlameReactor.DB.Models.Breeding", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstParentID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlameID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondParentID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ChildID");

                    b.HasIndex("FirstParentID");

                    b.HasIndex("FlameID");

                    b.HasIndex("SecondParentID");

                    b.ToTable("Breeding");
                });

            modelBuilder.Entity("FlameReactor.DB.Models.Flame", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenomePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Promiscuity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoPath")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("BirthID");

                    b.ToTable("Flames");
                });

            modelBuilder.Entity("FlameReactor.DB.Models.InteractionEvent", b =>
                {
                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("InteractionType")
                        .HasColumnType("TEXT");

                    b.HasKey("Timestamp", "IPAddress");

                    b.ToTable("InteractionEvent");
                });

            modelBuilder.Entity("FlameReactor.DB.Models.Vote", b =>
                {
                    b.Property<string>("IPAddress")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IPAddress", "FlameId");

                    b.ToTable("Vote");
                });

            modelBuilder.Entity("FlameReactor.DB.Models.Breeding", b =>
                {
                    b.HasOne("FlameReactor.DB.Models.Flame", "Child")
                        .WithMany()
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlameReactor.DB.Models.Flame", "FirstParent")
                        .WithMany()
                        .HasForeignKey("FirstParentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlameReactor.DB.Models.Flame", null)
                        .WithMany("Breedings")
                        .HasForeignKey("FlameID");

                    b.HasOne("FlameReactor.DB.Models.Flame", "SecondParent")
                        .WithMany()
                        .HasForeignKey("SecondParentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("FirstParent");

                    b.Navigation("SecondParent");
                });

            modelBuilder.Entity("FlameReactor.DB.Models.Flame", b =>
                {
                    b.HasOne("FlameReactor.DB.Models.Breeding", "Birth")
                        .WithMany()
                        .HasForeignKey("BirthID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Birth");
                });

            modelBuilder.Entity("FlameReactor.DB.Models.Flame", b =>
                {
                    b.Navigation("Breedings");
                });
#pragma warning restore 612, 618
        }
    }
}
