// <auto-generated />
using System;
using FlameReactor.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlameReactor.DB.Migrations
{
    [DbContext(typeof(FlameReactorContext))]
    [Migration("20210610155656_RemoveFlameFromInteractionEvent")]
    partial class RemoveFlameFromInteractionEvent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("FlameReactor.DB.Models.AccessEvent", b =>
                {
                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Timestamp", "IPAddress");

                    b.ToTable("AccessEvent");
                });

            modelBuilder.Entity("FlameReactor.DB.Models.Flame", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenomePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Promiscuity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoPath")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Flames");
                });

            modelBuilder.Entity("FlameReactor.DB.Models.InteractionEvent", b =>
                {
                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("InteractionType")
                        .HasColumnType("TEXT");

                    b.HasKey("Timestamp", "IPAddress");

                    b.ToTable("InteractionEvent");
                });

            modelBuilder.Entity("FlameReactor.DB.Models.Vote", b =>
                {
                    b.Property<string>("IPAddress")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IPAddress", "FlameId");

                    b.ToTable("Vote");
                });
#pragma warning restore 612, 618
        }
    }
}
